try {
    throw Error('Error')
} catch (error) {
    print(error)
}
